# Generated by Django 4.0 on 2022-09-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_artist_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
