# Generated by Django 4.0 on 2022-09-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_publisher_date_founded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
