# Generated by Django 4.0 on 2022-09-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_album_release_date_alter_album_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
