# Generated by Django 4.0 on 2022-09-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='submission_date',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
