# Generated by Django 4.0 on 2022-09-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_alter_album_submission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='submission_date',
        ),
    ]
