# Generated by Django 4.0 on 2022-09-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='date_founded',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
