# Generated by Django 4.0 on 2022-09-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_artist_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
